export const signatureList = [
    { id: 1, title: 'Netflix', src: require('../assets/icons/netflix.png') },
    { id: 2, title: 'Prime Video', src: require('../assets/icons/primeVideo.png') },
    { id: 3, title: 'YouTube', src: require('../assets/icons/youtube.png') },
    { id: 4, title: 'HBO Max', src: require('../assets/icons/hboMax.png') },
    { id: 5, title: 'Apple TV+', src: require('../assets/icons/appleTV.png') },
    { id: 6, title: 'Crunchyroll', src: require('../assets/icons/crunchyroll.png') },
    { id: 7, title: 'Disney +', src: require('../assets/icons/disneyPlus.png') },
    { id: 8, title: 'Start +', src: require('../assets/icons/starPlus.png') },
    { id: 9, title: 'Globo Play', src: require('../assets/icons/starPlus.png') },
    { id: 10, title: 'Game Pass', src: require('../assets/icons/starPlus.png') },
    { id: 11, title: 'PSN Plus', src: require('../assets/icons/starPlus.png') },
    { id: 12, title: 'Looke', src: require('../assets/icons/starPlus.png') },
    { id: 13, title: 'Telecine', src: require('../assets/icons/starPlus.png') },
    { id: 14, title: 'Mubi', src: require('../assets/icons/starPlus.png') },
    { id: 15, title: 'Mubi', src: require('../assets/icons/starPlus.png') },
    { id: 16, title: 'Spotify', src: require('../assets/icons/spotify.png') },
    { id: 17, title: 'Notion', src: require('../assets/icons/notion.png') },
];